//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/10/2014 1:38:39 PM
namespace Harris.Automation.ADC.Services.ListService.AdcDataService
{
    
    /// <summary>
    /// There are no comments for AdcModelContainer in the schema.
    /// </summary>
    public partial class AdcModelContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new AdcModelContainer object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AdcModelContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("AdcModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Harris.Automation.ADC.Services.ListService.AdcDataService", typeName.Substring(8)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Harris.Automation.ADC.Services.ListService.AdcDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AdcModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for AsRuns in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AsRun> AsRuns
        {
            get
            {
                if ((this._AsRuns == null))
                {
                    this._AsRuns = base.CreateQuery<AsRun>("AsRuns");
                }
                return this._AsRuns;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AsRun> _AsRuns;
        /// <summary>
        /// There are no comments for MediaInfoNotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MediaInfoNote> MediaInfoNotes
        {
            get
            {
                if ((this._MediaInfoNotes == null))
                {
                    this._MediaInfoNotes = base.CreateQuery<MediaInfoNote>("MediaInfoNotes");
                }
                return this._MediaInfoNotes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MediaInfoNote> _MediaInfoNotes;
        /// <summary>
        /// There are no comments for MediaInfos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MediaInfo> MediaInfos
        {
            get
            {
                if ((this._MediaInfos == null))
                {
                    this._MediaInfos = base.CreateQuery<MediaInfo>("MediaInfos");
                }
                return this._MediaInfos;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MediaInfo> _MediaInfos;
        /// <summary>
        /// There are no comments for SegmentInfoNotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SegmentInfoNote> SegmentInfoNotes
        {
            get
            {
                if ((this._SegmentInfoNotes == null))
                {
                    this._SegmentInfoNotes = base.CreateQuery<SegmentInfoNote>("SegmentInfoNotes");
                }
                return this._SegmentInfoNotes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SegmentInfoNote> _SegmentInfoNotes;
        /// <summary>
        /// There are no comments for SegmentInfos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SegmentInfo> SegmentInfos
        {
            get
            {
                if ((this._SegmentInfos == null))
                {
                    this._SegmentInfos = base.CreateQuery<SegmentInfo>("SegmentInfos");
                }
                return this._SegmentInfos;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SegmentInfo> _SegmentInfos;
        /// <summary>
        /// There are no comments for ContentTables in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ContentTable> ContentTables
        {
            get
            {
                if ((this._ContentTables == null))
                {
                    this._ContentTables = base.CreateQuery<ContentTable>("ContentTables");
                }
                return this._ContentTables;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ContentTable> _ContentTables;
        /// <summary>
        /// There are no comments for AsRuns in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAsRuns(AsRun asRun)
        {
            base.AddObject("AsRuns", asRun);
        }
        /// <summary>
        /// There are no comments for MediaInfoNotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMediaInfoNotes(MediaInfoNote mediaInfoNote)
        {
            base.AddObject("MediaInfoNotes", mediaInfoNote);
        }
        /// <summary>
        /// There are no comments for MediaInfos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMediaInfos(MediaInfo mediaInfo)
        {
            base.AddObject("MediaInfos", mediaInfo);
        }
        /// <summary>
        /// There are no comments for SegmentInfoNotes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSegmentInfoNotes(SegmentInfoNote segmentInfoNote)
        {
            base.AddObject("SegmentInfoNotes", segmentInfoNote);
        }
        /// <summary>
        /// There are no comments for SegmentInfos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSegmentInfos(SegmentInfo segmentInfo)
        {
            base.AddObject("SegmentInfos", segmentInfo);
        }
        /// <summary>
        /// There are no comments for ContentTables in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToContentTables(ContentTable contentTable)
        {
            base.AddObject("ContentTables", contentTable);
        }
    }
    /// <summary>
    /// There are no comments for AdcModel.AsRun in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AsRuns")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class AsRun : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AsRun object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="serverName">Initial value of ServerName.</param>
        /// <param name="listNumber">Initial value of ListNumber.</param>
        /// <param name="onAirDate">Initial value of OnAirDate.</param>
        /// <param name="onAirTime">Initial value of OnAirTime.</param>
        /// <param name="aDCEventId">Initial value of ADCEventId.</param>
        /// <param name="identifier">Initial value of Identifier.</param>
        /// <param name="eventType">Initial value of EventType.</param>
        /// <param name="actualDuration">Initial value of ActualDuration.</param>
        /// <param name="status">Initial value of Status.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AsRun CreateAsRun(long ID, string serverName, short listNumber, global::System.DateTime onAirDate, int onAirTime, global::System.Guid aDCEventId, string identifier, int eventType, int actualDuration, byte status)
        {
            AsRun asRun = new AsRun();
            asRun.Id = ID;
            asRun.ServerName = serverName;
            asRun.ListNumber = listNumber;
            asRun.OnAirDate = onAirDate;
            asRun.OnAirTime = onAirTime;
            asRun.ADCEventId = aDCEventId;
            asRun.Identifier = identifier;
            asRun.EventType = eventType;
            asRun.ActualDuration = actualDuration;
            asRun.Status = status;
            return asRun;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ServerName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ServerName
        {
            get
            {
                return this._ServerName;
            }
            set
            {
                this.OnServerNameChanging(value);
                this._ServerName = value;
                this.OnServerNameChanged();
                this.OnPropertyChanged("ServerName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ServerName;
        partial void OnServerNameChanging(string value);
        partial void OnServerNameChanged();
        /// <summary>
        /// There are no comments for Property ListNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short ListNumber
        {
            get
            {
                return this._ListNumber;
            }
            set
            {
                this.OnListNumberChanging(value);
                this._ListNumber = value;
                this.OnListNumberChanged();
                this.OnPropertyChanged("ListNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _ListNumber;
        partial void OnListNumberChanging(short value);
        partial void OnListNumberChanged();
        /// <summary>
        /// There are no comments for Property OnAirDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime OnAirDate
        {
            get
            {
                return this._OnAirDate;
            }
            set
            {
                this.OnOnAirDateChanging(value);
                this._OnAirDate = value;
                this.OnOnAirDateChanged();
                this.OnPropertyChanged("OnAirDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _OnAirDate;
        partial void OnOnAirDateChanging(global::System.DateTime value);
        partial void OnOnAirDateChanged();
        /// <summary>
        /// There are no comments for Property OnAirTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OnAirTime
        {
            get
            {
                return this._OnAirTime;
            }
            set
            {
                this.OnOnAirTimeChanging(value);
                this._OnAirTime = value;
                this.OnOnAirTimeChanged();
                this.OnPropertyChanged("OnAirTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OnAirTime;
        partial void OnOnAirTimeChanging(int value);
        partial void OnOnAirTimeChanged();
        /// <summary>
        /// There are no comments for Property ADCEventId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ADCEventId
        {
            get
            {
                return this._ADCEventId;
            }
            set
            {
                this.OnADCEventIdChanging(value);
                this._ADCEventId = value;
                this.OnADCEventIdChanged();
                this.OnPropertyChanged("ADCEventId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ADCEventId;
        partial void OnADCEventIdChanging(global::System.Guid value);
        partial void OnADCEventIdChanged();
        /// <summary>
        /// There are no comments for Property Identifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identifier
        {
            get
            {
                return this._Identifier;
            }
            set
            {
                this.OnIdentifierChanging(value);
                this._Identifier = value;
                this.OnIdentifierChanged();
                this.OnPropertyChanged("Identifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identifier;
        partial void OnIdentifierChanging(string value);
        partial void OnIdentifierChanged();
        /// <summary>
        /// There are no comments for Property ReconcileKey in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ReconcileKey
        {
            get
            {
                return this._ReconcileKey;
            }
            set
            {
                this.OnReconcileKeyChanging(value);
                this._ReconcileKey = value;
                this.OnReconcileKeyChanged();
                this.OnPropertyChanged("ReconcileKey");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ReconcileKey;
        partial void OnReconcileKeyChanging(string value);
        partial void OnReconcileKeyChanged();
        /// <summary>
        /// There are no comments for Property CompileTape in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CompileTape
        {
            get
            {
                return this._CompileTape;
            }
            set
            {
                this.OnCompileTapeChanging(value);
                this._CompileTape = value;
                this.OnCompileTapeChanged();
                this.OnPropertyChanged("CompileTape");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CompileTape;
        partial void OnCompileTapeChanging(string value);
        partial void OnCompileTapeChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property EventType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventType
        {
            get
            {
                return this._EventType;
            }
            set
            {
                this.OnEventTypeChanging(value);
                this._EventType = value;
                this.OnEventTypeChanged();
                this.OnPropertyChanged("EventType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventType;
        partial void OnEventTypeChanging(int value);
        partial void OnEventTypeChanged();
        /// <summary>
        /// There are no comments for Property SecondaryEventName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SecondaryEventName
        {
            get
            {
                return this._SecondaryEventName;
            }
            set
            {
                this.OnSecondaryEventNameChanging(value);
                this._SecondaryEventName = value;
                this.OnSecondaryEventNameChanged();
                this.OnPropertyChanged("SecondaryEventName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SecondaryEventName;
        partial void OnSecondaryEventNameChanging(string value);
        partial void OnSecondaryEventNameChanged();
        /// <summary>
        /// There are no comments for Property ActualDuration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ActualDuration
        {
            get
            {
                return this._ActualDuration;
            }
            set
            {
                this.OnActualDurationChanging(value);
                this._ActualDuration = value;
                this.OnActualDurationChanged();
                this.OnPropertyChanged("ActualDuration");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ActualDuration;
        partial void OnActualDurationChanging(int value);
        partial void OnActualDurationChanged();
        /// <summary>
        /// There are no comments for Property StartOfMedia in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> StartOfMedia
        {
            get
            {
                return this._StartOfMedia;
            }
            set
            {
                this.OnStartOfMediaChanging(value);
                this._StartOfMedia = value;
                this.OnStartOfMediaChanged();
                this.OnPropertyChanged("StartOfMedia");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _StartOfMedia;
        partial void OnStartOfMediaChanging(global::System.Nullable<int> value);
        partial void OnStartOfMediaChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _Status;
        partial void OnStatusChanging(byte value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Device in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Device
        {
            get
            {
                return this._Device;
            }
            set
            {
                this.OnDeviceChanging(value);
                this._Device = value;
                this.OnDeviceChanged();
                this.OnPropertyChanged("Device");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Device;
        partial void OnDeviceChanging(string value);
        partial void OnDeviceChanged();
        /// <summary>
        /// There are no comments for Property HardStart in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> HardStart
        {
            get
            {
                return this._HardStart;
            }
            set
            {
                this.OnHardStartChanging(value);
                this._HardStart = value;
                this.OnHardStartChanged();
                this.OnPropertyChanged("HardStart");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _HardStart;
        partial void OnHardStartChanging(global::System.Nullable<bool> value);
        partial void OnHardStartChanged();
        /// <summary>
        /// There are no comments for Property SegmentNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> SegmentNumber
        {
            get
            {
                return this._SegmentNumber;
            }
            set
            {
                this.OnSegmentNumberChanging(value);
                this._SegmentNumber = value;
                this.OnSegmentNumberChanged();
                this.OnPropertyChanged("SegmentNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _SegmentNumber;
        partial void OnSegmentNumberChanging(global::System.Nullable<byte> value);
        partial void OnSegmentNumberChanged();
        /// <summary>
        /// There are no comments for Property Channel in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> Channel
        {
            get
            {
                return this._Channel;
            }
            set
            {
                this.OnChannelChanging(value);
                this._Channel = value;
                this.OnChannelChanged();
                this.OnPropertyChanged("Channel");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _Channel;
        partial void OnChannelChanging(global::System.Nullable<byte> value);
        partial void OnChannelChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdcModel.MediaInfoNote in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MediaInfo
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MediaInfoNotes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MediaInfo")]
    public partial class MediaInfoNote : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MediaInfoNote object.
        /// </summary>
        /// <param name="mediaInfo">Initial value of MediaInfo.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MediaInfoNote CreateMediaInfoNote(int mediaInfo)
        {
            MediaInfoNote mediaInfoNote = new MediaInfoNote();
            mediaInfoNote.MediaInfo = mediaInfo;
            return mediaInfoNote;
        }
        /// <summary>
        /// There are no comments for Property MediaInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int MediaInfo
        {
            get
            {
                return this._MediaInfo;
            }
            set
            {
                this.OnMediaInfoChanging(value);
                this._MediaInfo = value;
                this.OnMediaInfoChanged();
                this.OnPropertyChanged("MediaInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _MediaInfo;
        partial void OnMediaInfoChanging(int value);
        partial void OnMediaInfoChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property NoteDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> NoteDateTime
        {
            get
            {
                return this._NoteDateTime;
            }
            set
            {
                this.OnNoteDateTimeChanging(value);
                this._NoteDateTime = value;
                this.OnNoteDateTimeChanged();
                this.OnPropertyChanged("NoteDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _NoteDateTime;
        partial void OnNoteDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnNoteDateTimeChanged();
        /// <summary>
        /// There are no comments for Property AdcExtendedInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AdcExtendedInfo
        {
            get
            {
                return this._AdcExtendedInfo;
            }
            set
            {
                this.OnAdcExtendedInfoChanging(value);
                this._AdcExtendedInfo = value;
                this.OnAdcExtendedInfoChanged();
                this.OnPropertyChanged("AdcExtendedInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AdcExtendedInfo;
        partial void OnAdcExtendedInfoChanging(string value);
        partial void OnAdcExtendedInfoChanged();
        /// <summary>
        /// There are no comments for Property ExtendedInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ExtendedInfo
        {
            get
            {
                return this._ExtendedInfo;
            }
            set
            {
                this.OnExtendedInfoChanging(value);
                this._ExtendedInfo = value;
                this.OnExtendedInfoChanged();
                this.OnPropertyChanged("ExtendedInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ExtendedInfo;
        partial void OnExtendedInfoChanging(string value);
        partial void OnExtendedInfoChanged();
        /// <summary>
        /// There are no comments for MediaInfoValue in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MediaInfo MediaInfoValue
        {
            get
            {
                return this._MediaInfoValue;
            }
            set
            {
                this._MediaInfoValue = value;
                this.OnPropertyChanged("MediaInfoValue");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MediaInfo _MediaInfoValue;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdcModel.MediaInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MediaInfos")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MediaInfo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MediaInfo object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="identifier">Initial value of Identifier.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MediaInfo CreateMediaInfo(int ID, byte[] version, string identifier)
        {
            MediaInfo mediaInfo = new MediaInfo();
            mediaInfo.Id = ID;
            mediaInfo.Version = version;
            mediaInfo.Identifier = identifier;
            return mediaInfo;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property BoxIdentifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BoxIdentifier
        {
            get
            {
                return this._BoxIdentifier;
            }
            set
            {
                this.OnBoxIdentifierChanging(value);
                this._BoxIdentifier = value;
                this.OnBoxIdentifierChanged();
                this.OnPropertyChanged("BoxIdentifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BoxIdentifier;
        partial void OnBoxIdentifierChanging(string value);
        partial void OnBoxIdentifierChanged();
        /// <summary>
        /// There are no comments for Property AltIdentifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AltIdentifier
        {
            get
            {
                return this._AltIdentifier;
            }
            set
            {
                this.OnAltIdentifierChanging(value);
                this._AltIdentifier = value;
                this.OnAltIdentifierChanged();
                this.OnPropertyChanged("AltIdentifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AltIdentifier;
        partial void OnAltIdentifierChanging(string value);
        partial void OnAltIdentifierChanged();
        /// <summary>
        /// There are no comments for Property OrgIdentifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OrgIdentifier
        {
            get
            {
                return this._OrgIdentifier;
            }
            set
            {
                this.OnOrgIdentifierChanging(value);
                this._OrgIdentifier = value;
                this.OnOrgIdentifierChanged();
                this.OnPropertyChanged("OrgIdentifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OrgIdentifier;
        partial void OnOrgIdentifierChanging(string value);
        partial void OnOrgIdentifierChanged();
        /// <summary>
        /// There are no comments for Property UserString in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserString
        {
            get
            {
                return this._UserString;
            }
            set
            {
                this.OnUserStringChanging(value);
                this._UserString = value;
                this.OnUserStringChanged();
                this.OnPropertyChanged("UserString");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserString;
        partial void OnUserStringChanging(string value);
        partial void OnUserStringChanged();
        /// <summary>
        /// There are no comments for Property UserData1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserData1
        {
            get
            {
                return this._UserData1;
            }
            set
            {
                this.OnUserData1Changing(value);
                this._UserData1 = value;
                this.OnUserData1Changed();
                this.OnPropertyChanged("UserData1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserData1;
        partial void OnUserData1Changing(string value);
        partial void OnUserData1Changed();
        /// <summary>
        /// There are no comments for Property UserData2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserData2
        {
            get
            {
                return this._UserData2;
            }
            set
            {
                this.OnUserData2Changing(value);
                this._UserData2 = value;
                this.OnUserData2Changed();
                this.OnPropertyChanged("UserData2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserData2;
        partial void OnUserData2Changing(string value);
        partial void OnUserData2Changed();
        /// <summary>
        /// There are no comments for Property Operator in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Operator
        {
            get
            {
                return this._Operator;
            }
            set
            {
                this.OnOperatorChanging(value);
                this._Operator = value;
                this.OnOperatorChanged();
                this.OnPropertyChanged("Operator");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Operator;
        partial void OnOperatorChanging(string value);
        partial void OnOperatorChanged();
        /// <summary>
        /// There are no comments for Property StartOfMedia in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> StartOfMedia
        {
            get
            {
                return this._StartOfMedia;
            }
            set
            {
                this.OnStartOfMediaChanging(value);
                this._StartOfMedia = value;
                this.OnStartOfMediaChanged();
                this.OnPropertyChanged("StartOfMedia");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _StartOfMedia;
        partial void OnStartOfMediaChanging(global::System.Nullable<int> value);
        partial void OnStartOfMediaChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Duration;
        partial void OnDurationChanging(global::System.Nullable<int> value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property PlayNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> PlayNumber
        {
            get
            {
                return this._PlayNumber;
            }
            set
            {
                this.OnPlayNumberChanging(value);
                this._PlayNumber = value;
                this.OnPlayNumberChanged();
                this.OnPropertyChanged("PlayNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _PlayNumber;
        partial void OnPlayNumberChanging(global::System.Nullable<int> value);
        partial void OnPlayNumberChanged();
        /// <summary>
        /// There are no comments for Property LabelType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> LabelType
        {
            get
            {
                return this._LabelType;
            }
            set
            {
                this.OnLabelTypeChanging(value);
                this._LabelType = value;
                this.OnLabelTypeChanged();
                this.OnPropertyChanged("LabelType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _LabelType;
        partial void OnLabelTypeChanging(global::System.Nullable<int> value);
        partial void OnLabelTypeChanged();
        /// <summary>
        /// There are no comments for Property VideoFormat in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> VideoFormat
        {
            get
            {
                return this._VideoFormat;
            }
            set
            {
                this.OnVideoFormatChanging(value);
                this._VideoFormat = value;
                this.OnVideoFormatChanged();
                this.OnPropertyChanged("VideoFormat");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _VideoFormat;
        partial void OnVideoFormatChanging(global::System.Nullable<int> value);
        partial void OnVideoFormatChanged();
        /// <summary>
        /// There are no comments for Property VideoQuality in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> VideoQuality
        {
            get
            {
                return this._VideoQuality;
            }
            set
            {
                this.OnVideoQualityChanging(value);
                this._VideoQuality = value;
                this.OnVideoQualityChanged();
                this.OnPropertyChanged("VideoQuality");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _VideoQuality;
        partial void OnVideoQualityChanging(global::System.Nullable<int> value);
        partial void OnVideoQualityChanged();
        /// <summary>
        /// There are no comments for Property AudioFormat in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> AudioFormat
        {
            get
            {
                return this._AudioFormat;
            }
            set
            {
                this.OnAudioFormatChanging(value);
                this._AudioFormat = value;
                this.OnAudioFormatChanged();
                this.OnPropertyChanged("AudioFormat");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _AudioFormat;
        partial void OnAudioFormatChanging(global::System.Nullable<int> value);
        partial void OnAudioFormatChanged();
        /// <summary>
        /// There are no comments for Property MadeDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> MadeDateTime
        {
            get
            {
                return this._MadeDateTime;
            }
            set
            {
                this.OnMadeDateTimeChanging(value);
                this._MadeDateTime = value;
                this.OnMadeDateTimeChanged();
                this.OnPropertyChanged("MadeDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _MadeDateTime;
        partial void OnMadeDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnMadeDateTimeChanged();
        /// <summary>
        /// There are no comments for Property PlayDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PlayDateTime
        {
            get
            {
                return this._PlayDateTime;
            }
            set
            {
                this.OnPlayDateTimeChanging(value);
                this._PlayDateTime = value;
                this.OnPlayDateTimeChanged();
                this.OnPropertyChanged("PlayDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PlayDateTime;
        partial void OnPlayDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPlayDateTimeChanged();
        /// <summary>
        /// There are no comments for Property AirDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> AirDateTime
        {
            get
            {
                return this._AirDateTime;
            }
            set
            {
                this.OnAirDateTimeChanging(value);
                this._AirDateTime = value;
                this.OnAirDateTimeChanged();
                this.OnPropertyChanged("AirDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _AirDateTime;
        partial void OnAirDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAirDateTimeChanged();
        /// <summary>
        /// There are no comments for Property PurgeDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PurgeDateTime
        {
            get
            {
                return this._PurgeDateTime;
            }
            set
            {
                this.OnPurgeDateTimeChanging(value);
                this._PurgeDateTime = value;
                this.OnPurgeDateTimeChanged();
                this.OnPropertyChanged("PurgeDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PurgeDateTime;
        partial void OnPurgeDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPurgeDateTimeChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Version
        {
            get
            {
                if ((this._Version != null))
                {
                    return ((byte[])(this._Version.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Version;
        partial void OnVersionChanging(byte[] value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Identifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identifier
        {
            get
            {
                return this._Identifier;
            }
            set
            {
                this.OnIdentifierChanging(value);
                this._Identifier = value;
                this.OnIdentifierChanged();
                this.OnPropertyChanged("Identifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identifier;
        partial void OnIdentifierChanging(string value);
        partial void OnIdentifierChanged();
        /// <summary>
        /// There are no comments for Property ContentId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ContentId
        {
            get
            {
                return this._ContentId;
            }
            set
            {
                this.OnContentIdChanging(value);
                this._ContentId = value;
                this.OnContentIdChanged();
                this.OnPropertyChanged("ContentId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ContentId;
        partial void OnContentIdChanging(global::System.Nullable<int> value);
        partial void OnContentIdChanged();
        /// <summary>
        /// There are no comments for MediaInfoNote in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MediaInfoNote MediaInfoNote
        {
            get
            {
                return this._MediaInfoNote;
            }
            set
            {
                this._MediaInfoNote = value;
                this.OnPropertyChanged("MediaInfoNote");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MediaInfoNote _MediaInfoNote;
        /// <summary>
        /// There are no comments for SegmentInfos in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SegmentInfo> SegmentInfos
        {
            get
            {
                return this._SegmentInfos;
            }
            set
            {
                this._SegmentInfos = value;
                this.OnPropertyChanged("SegmentInfos");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SegmentInfo> _SegmentInfos = new global::System.Data.Services.Client.DataServiceCollection<SegmentInfo>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for ContentTable in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ContentTable ContentTable
        {
            get
            {
                return this._ContentTable;
            }
            set
            {
                this._ContentTable = value;
                this.OnPropertyChanged("ContentTable");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ContentTable _ContentTable;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdcModel.SegmentInfoNote in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SegmentInfo
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SegmentInfoNotes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SegmentInfo")]
    public partial class SegmentInfoNote : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SegmentInfoNote object.
        /// </summary>
        /// <param name="segmentInfo">Initial value of SegmentInfo.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SegmentInfoNote CreateSegmentInfoNote(int segmentInfo)
        {
            SegmentInfoNote segmentInfoNote = new SegmentInfoNote();
            segmentInfoNote.SegmentInfo = segmentInfo;
            return segmentInfoNote;
        }
        /// <summary>
        /// There are no comments for Property SegmentInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SegmentInfo
        {
            get
            {
                return this._SegmentInfo;
            }
            set
            {
                this.OnSegmentInfoChanging(value);
                this._SegmentInfo = value;
                this.OnSegmentInfoChanged();
                this.OnPropertyChanged("SegmentInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SegmentInfo;
        partial void OnSegmentInfoChanging(int value);
        partial void OnSegmentInfoChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property NoteDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> NoteDateTime
        {
            get
            {
                return this._NoteDateTime;
            }
            set
            {
                this.OnNoteDateTimeChanging(value);
                this._NoteDateTime = value;
                this.OnNoteDateTimeChanged();
                this.OnPropertyChanged("NoteDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _NoteDateTime;
        partial void OnNoteDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnNoteDateTimeChanged();
        /// <summary>
        /// There are no comments for Property AdcExtendedInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AdcExtendedInfo
        {
            get
            {
                return this._AdcExtendedInfo;
            }
            set
            {
                this.OnAdcExtendedInfoChanging(value);
                this._AdcExtendedInfo = value;
                this.OnAdcExtendedInfoChanged();
                this.OnPropertyChanged("AdcExtendedInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AdcExtendedInfo;
        partial void OnAdcExtendedInfoChanging(string value);
        partial void OnAdcExtendedInfoChanged();
        /// <summary>
        /// There are no comments for Property ExtendedInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ExtendedInfo
        {
            get
            {
                return this._ExtendedInfo;
            }
            set
            {
                this.OnExtendedInfoChanging(value);
                this._ExtendedInfo = value;
                this.OnExtendedInfoChanged();
                this.OnPropertyChanged("ExtendedInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ExtendedInfo;
        partial void OnExtendedInfoChanging(string value);
        partial void OnExtendedInfoChanged();
        /// <summary>
        /// There are no comments for SegmentInfoValue in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SegmentInfo SegmentInfoValue
        {
            get
            {
                return this._SegmentInfoValue;
            }
            set
            {
                this._SegmentInfoValue = value;
                this.OnPropertyChanged("SegmentInfoValue");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SegmentInfo _SegmentInfoValue;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdcModel.SegmentInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SegmentInfos")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SegmentInfo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SegmentInfo object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="segHeader">Initial value of SegHeader.</param>
        /// <param name="segmentNum">Initial value of SegmentNum.</param>
        /// <param name="segmentType">Initial value of SegmentType.</param>
        /// <param name="startOfMedia">Initial value of StartOfMedia.</param>
        /// <param name="duration">Initial value of Duration.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SegmentInfo CreateSegmentInfo(int ID, string title, int segHeader, int segmentNum, int segmentType, int startOfMedia, int duration)
        {
            SegmentInfo segmentInfo = new SegmentInfo();
            segmentInfo.Id = ID;
            segmentInfo.Title = title;
            segmentInfo.SegHeader = segHeader;
            segmentInfo.SegmentNum = segmentNum;
            segmentInfo.SegmentType = segmentType;
            segmentInfo.StartOfMedia = startOfMedia;
            segmentInfo.Duration = duration;
            return segmentInfo;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property SegHeader in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SegHeader
        {
            get
            {
                return this._SegHeader;
            }
            set
            {
                this.OnSegHeaderChanging(value);
                this._SegHeader = value;
                this.OnSegHeaderChanged();
                this.OnPropertyChanged("SegHeader");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SegHeader;
        partial void OnSegHeaderChanging(int value);
        partial void OnSegHeaderChanged();
        /// <summary>
        /// There are no comments for Property SegmentNum in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SegmentNum
        {
            get
            {
                return this._SegmentNum;
            }
            set
            {
                this.OnSegmentNumChanging(value);
                this._SegmentNum = value;
                this.OnSegmentNumChanged();
                this.OnPropertyChanged("SegmentNum");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SegmentNum;
        partial void OnSegmentNumChanging(int value);
        partial void OnSegmentNumChanged();
        /// <summary>
        /// There are no comments for Property SegmentType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SegmentType
        {
            get
            {
                return this._SegmentType;
            }
            set
            {
                this.OnSegmentTypeChanging(value);
                this._SegmentType = value;
                this.OnSegmentTypeChanged();
                this.OnPropertyChanged("SegmentType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SegmentType;
        partial void OnSegmentTypeChanging(int value);
        partial void OnSegmentTypeChanged();
        /// <summary>
        /// There are no comments for Property StartOfMedia in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StartOfMedia
        {
            get
            {
                return this._StartOfMedia;
            }
            set
            {
                this.OnStartOfMediaChanging(value);
                this._StartOfMedia = value;
                this.OnStartOfMediaChanged();
                this.OnPropertyChanged("StartOfMedia");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StartOfMedia;
        partial void OnStartOfMediaChanging(int value);
        partial void OnStartOfMediaChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Duration;
        partial void OnDurationChanging(int value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for MediaInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MediaInfo MediaInfo
        {
            get
            {
                return this._MediaInfo;
            }
            set
            {
                this._MediaInfo = value;
                this.OnPropertyChanged("MediaInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MediaInfo _MediaInfo;
        /// <summary>
        /// There are no comments for SegmentInfoNote in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SegmentInfoNote SegmentInfoNote
        {
            get
            {
                return this._SegmentInfoNote;
            }
            set
            {
                this._SegmentInfoNote = value;
                this.OnPropertyChanged("SegmentInfoNote");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SegmentInfoNote _SegmentInfoNote;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AdcModel.ContentTable in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ContentTables")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ContentTable : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ContentTable object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="content">Initial value of Content.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ContentTable CreateContentTable(int ID, string content)
        {
            ContentTable contentTable = new ContentTable();
            contentTable.Id = ID;
            contentTable.Content = content;
            return contentTable;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this._Content = value;
                this.OnContentChanged();
                this.OnPropertyChanged("Content");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
