//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/10/2014 1:39:10 PM
namespace Harris.Automation.ADC.Services.ListService.AsdbDataService
{
    
    /// <summary>
    /// There are no comments for ASDBModelContainer in the schema.
    /// </summary>
    public partial class ASDBModelContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ASDBModelContainer object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ASDBModelContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ASDBModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Harris.Automation.ADC.Services.ListService.AsdbDataService", typeName.Substring(9)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Harris.Automation.ADC.Services.ListService.AsdbDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ASDBModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ASDBs in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ASDB> ASDBs
        {
            get
            {
                if ((this._ASDBs == null))
                {
                    this._ASDBs = base.CreateQuery<ASDB>("ASDBs");
                }
                return this._ASDBs;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ASDB> _ASDBs;
        /// <summary>
        /// There are no comments for ASSEGs in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ASSEG> ASSEGs
        {
            get
            {
                if ((this._ASSEGs == null))
                {
                    this._ASSEGs = base.CreateQuery<ASSEG>("ASSEGs");
                }
                return this._ASSEGs;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ASSEG> _ASSEGs;
        /// <summary>
        /// There are no comments for ASDBs in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToASDBs(ASDB aSDB)
        {
            base.AddObject("ASDBs", aSDB);
        }
        /// <summary>
        /// There are no comments for ASSEGs in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToASSEGs(ASSEG aSSEG)
        {
            base.AddObject("ASSEGs", aSSEG);
        }
    }
    /// <summary>
    /// There are no comments for ASDBModel.ASDB in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Type
    /// Identifier
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ASDBs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Type", "Identifier")]
    public partial class ASDB : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ASDB object.
        /// </summary>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="identifier">Initial value of Identifier.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ASDB CreateASDB(string type, string identifier)
        {
            ASDB aSDB = new ASDB();
            aSDB.Type = type;
            aSDB.Identifier = identifier;
            return aSDB;
        }
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Identifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identifier
        {
            get
            {
                return this._Identifier;
            }
            set
            {
                this.OnIdentifierChanging(value);
                this._Identifier = value;
                this.OnIdentifierChanged();
                this.OnPropertyChanged("Identifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identifier;
        partial void OnIdentifierChanging(string value);
        partial void OnIdentifierChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property BoxIdentifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BoxIdentifier
        {
            get
            {
                return this._BoxIdentifier;
            }
            set
            {
                this.OnBoxIdentifierChanging(value);
                this._BoxIdentifier = value;
                this.OnBoxIdentifierChanged();
                this.OnPropertyChanged("BoxIdentifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BoxIdentifier;
        partial void OnBoxIdentifierChanging(string value);
        partial void OnBoxIdentifierChanged();
        /// <summary>
        /// There are no comments for Property AltIdentifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AltIdentifier
        {
            get
            {
                return this._AltIdentifier;
            }
            set
            {
                this.OnAltIdentifierChanging(value);
                this._AltIdentifier = value;
                this.OnAltIdentifierChanged();
                this.OnPropertyChanged("AltIdentifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AltIdentifier;
        partial void OnAltIdentifierChanging(string value);
        partial void OnAltIdentifierChanged();
        /// <summary>
        /// There are no comments for Property OrgIdentifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OrgIdentifier
        {
            get
            {
                return this._OrgIdentifier;
            }
            set
            {
                this.OnOrgIdentifierChanging(value);
                this._OrgIdentifier = value;
                this.OnOrgIdentifierChanged();
                this.OnPropertyChanged("OrgIdentifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OrgIdentifier;
        partial void OnOrgIdentifierChanging(string value);
        partial void OnOrgIdentifierChanged();
        /// <summary>
        /// There are no comments for Property UserString in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserString
        {
            get
            {
                return this._UserString;
            }
            set
            {
                this.OnUserStringChanging(value);
                this._UserString = value;
                this.OnUserStringChanged();
                this.OnPropertyChanged("UserString");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserString;
        partial void OnUserStringChanging(string value);
        partial void OnUserStringChanged();
        /// <summary>
        /// There are no comments for Property UserData1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserData1
        {
            get
            {
                return this._UserData1;
            }
            set
            {
                this.OnUserData1Changing(value);
                this._UserData1 = value;
                this.OnUserData1Changed();
                this.OnPropertyChanged("UserData1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserData1;
        partial void OnUserData1Changing(string value);
        partial void OnUserData1Changed();
        /// <summary>
        /// There are no comments for Property UserData2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserData2
        {
            get
            {
                return this._UserData2;
            }
            set
            {
                this.OnUserData2Changing(value);
                this._UserData2 = value;
                this.OnUserData2Changed();
                this.OnPropertyChanged("UserData2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserData2;
        partial void OnUserData2Changing(string value);
        partial void OnUserData2Changed();
        /// <summary>
        /// There are no comments for Property Operator in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Operator
        {
            get
            {
                return this._Operator;
            }
            set
            {
                this.OnOperatorChanging(value);
                this._Operator = value;
                this.OnOperatorChanged();
                this.OnPropertyChanged("Operator");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Operator;
        partial void OnOperatorChanging(string value);
        partial void OnOperatorChanged();
        /// <summary>
        /// There are no comments for Property StartOfMessage in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> StartOfMessage
        {
            get
            {
                return this._StartOfMessage;
            }
            set
            {
                this.OnStartOfMessageChanging(value);
                this._StartOfMessage = value;
                this.OnStartOfMessageChanged();
                this.OnPropertyChanged("StartOfMessage");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _StartOfMessage;
        partial void OnStartOfMessageChanging(global::System.Nullable<int> value);
        partial void OnStartOfMessageChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Duration;
        partial void OnDurationChanging(global::System.Nullable<int> value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property PlayNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> PlayNumber
        {
            get
            {
                return this._PlayNumber;
            }
            set
            {
                this.OnPlayNumberChanging(value);
                this._PlayNumber = value;
                this.OnPlayNumberChanged();
                this.OnPropertyChanged("PlayNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _PlayNumber;
        partial void OnPlayNumberChanging(global::System.Nullable<short> value);
        partial void OnPlayNumberChanged();
        /// <summary>
        /// There are no comments for Property LabelType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> LabelType
        {
            get
            {
                return this._LabelType;
            }
            set
            {
                this.OnLabelTypeChanging(value);
                this._LabelType = value;
                this.OnLabelTypeChanged();
                this.OnPropertyChanged("LabelType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _LabelType;
        partial void OnLabelTypeChanging(global::System.Nullable<byte> value);
        partial void OnLabelTypeChanged();
        /// <summary>
        /// There are no comments for Property VideoFormat in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> VideoFormat
        {
            get
            {
                return this._VideoFormat;
            }
            set
            {
                this.OnVideoFormatChanging(value);
                this._VideoFormat = value;
                this.OnVideoFormatChanged();
                this.OnPropertyChanged("VideoFormat");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _VideoFormat;
        partial void OnVideoFormatChanging(global::System.Nullable<byte> value);
        partial void OnVideoFormatChanged();
        /// <summary>
        /// There are no comments for Property VideoQuality in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> VideoQuality
        {
            get
            {
                return this._VideoQuality;
            }
            set
            {
                this.OnVideoQualityChanging(value);
                this._VideoQuality = value;
                this.OnVideoQualityChanged();
                this.OnPropertyChanged("VideoQuality");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _VideoQuality;
        partial void OnVideoQualityChanging(global::System.Nullable<byte> value);
        partial void OnVideoQualityChanged();
        /// <summary>
        /// There are no comments for Property AudioFormat in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> AudioFormat
        {
            get
            {
                return this._AudioFormat;
            }
            set
            {
                this.OnAudioFormatChanging(value);
                this._AudioFormat = value;
                this.OnAudioFormatChanged();
                this.OnPropertyChanged("AudioFormat");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _AudioFormat;
        partial void OnAudioFormatChanging(global::System.Nullable<byte> value);
        partial void OnAudioFormatChanged();
        /// <summary>
        /// There are no comments for Property MadeDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> MadeDateTime
        {
            get
            {
                return this._MadeDateTime;
            }
            set
            {
                this.OnMadeDateTimeChanging(value);
                this._MadeDateTime = value;
                this.OnMadeDateTimeChanged();
                this.OnPropertyChanged("MadeDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _MadeDateTime;
        partial void OnMadeDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnMadeDateTimeChanged();
        /// <summary>
        /// There are no comments for Property PlayDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PlayDateTime
        {
            get
            {
                return this._PlayDateTime;
            }
            set
            {
                this.OnPlayDateTimeChanging(value);
                this._PlayDateTime = value;
                this.OnPlayDateTimeChanged();
                this.OnPropertyChanged("PlayDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PlayDateTime;
        partial void OnPlayDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPlayDateTimeChanged();
        /// <summary>
        /// There are no comments for Property AirDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> AirDateTime
        {
            get
            {
                return this._AirDateTime;
            }
            set
            {
                this.OnAirDateTimeChanging(value);
                this._AirDateTime = value;
                this.OnAirDateTimeChanged();
                this.OnPropertyChanged("AirDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _AirDateTime;
        partial void OnAirDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnAirDateTimeChanged();
        /// <summary>
        /// There are no comments for Property PurgeDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PurgeDateTime
        {
            get
            {
                return this._PurgeDateTime;
            }
            set
            {
                this.OnPurgeDateTimeChanging(value);
                this._PurgeDateTime = value;
                this.OnPurgeDateTimeChanged();
                this.OnPropertyChanged("PurgeDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PurgeDateTime;
        partial void OnPurgeDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPurgeDateTimeChanged();
        /// <summary>
        /// There are no comments for Property NoteDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> NoteDateTime
        {
            get
            {
                return this._NoteDateTime;
            }
            set
            {
                this.OnNoteDateTimeChanging(value);
                this._NoteDateTime = value;
                this.OnNoteDateTimeChanged();
                this.OnPropertyChanged("NoteDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _NoteDateTime;
        partial void OnNoteDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnNoteDateTimeChanged();
        /// <summary>
        /// There are no comments for Property NoteContent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NoteContent
        {
            get
            {
                return this._NoteContent;
            }
            set
            {
                this.OnNoteContentChanging(value);
                this._NoteContent = value;
                this.OnNoteContentChanged();
                this.OnPropertyChanged("NoteContent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NoteContent;
        partial void OnNoteContentChanging(string value);
        partial void OnNoteContentChanged();
        /// <summary>
        /// There are no comments for Property AFD in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> AFD
        {
            get
            {
                return this._AFD;
            }
            set
            {
                this.OnAFDChanging(value);
                this._AFD = value;
                this.OnAFDChanged();
                this.OnPropertyChanged("AFD");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _AFD;
        partial void OnAFDChanging(global::System.Nullable<byte> value);
        partial void OnAFDChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this._Rating = value;
                this.OnRatingChanged();
                this.OnPropertyChanged("Rating");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Rating;
        partial void OnRatingChanging(string value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for Property DialNorm in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DialNorm
        {
            get
            {
                return this._DialNorm;
            }
            set
            {
                this.OnDialNormChanging(value);
                this._DialNorm = value;
                this.OnDialNormChanged();
                this.OnPropertyChanged("DialNorm");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DialNorm;
        partial void OnDialNormChanging(global::System.Nullable<int> value);
        partial void OnDialNormChanged();
        /// <summary>
        /// There are no comments for Property ShowID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShowID
        {
            get
            {
                return this._ShowID;
            }
            set
            {
                this.OnShowIDChanging(value);
                this._ShowID = value;
                this.OnShowIDChanged();
                this.OnPropertyChanged("ShowID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShowID;
        partial void OnShowIDChanging(string value);
        partial void OnShowIDChanged();
        /// <summary>
        /// There are no comments for Property ShowDescription in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShowDescription
        {
            get
            {
                return this._ShowDescription;
            }
            set
            {
                this.OnShowDescriptionChanging(value);
                this._ShowDescription = value;
                this.OnShowDescriptionChanged();
                this.OnPropertyChanged("ShowDescription");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShowDescription;
        partial void OnShowDescriptionChanging(string value);
        partial void OnShowDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ClosedCaption in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> ClosedCaption
        {
            get
            {
                return this._ClosedCaption;
            }
            set
            {
                this.OnClosedCaptionChanging(value);
                this._ClosedCaption = value;
                this.OnClosedCaptionChanged();
                this.OnPropertyChanged("ClosedCaption");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _ClosedCaption;
        partial void OnClosedCaptionChanging(global::System.Nullable<byte> value);
        partial void OnClosedCaptionChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this._Content = value;
                this.OnContentChanged();
                this.OnPropertyChanged("Content");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ASDBModel.ASSEG in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Type
    /// Identifier
    /// SegNum
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ASSEGs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Type", "Identifier", "SegNum")]
    public partial class ASSEG : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ASSEG object.
        /// </summary>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="identifier">Initial value of Identifier.</param>
        /// <param name="segNum">Initial value of SegNum.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ASSEG CreateASSEG(string type, string identifier, short segNum)
        {
            ASSEG aSSEG = new ASSEG();
            aSSEG.Type = type;
            aSSEG.Identifier = identifier;
            aSSEG.SegNum = segNum;
            return aSSEG;
        }
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Identifier in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identifier
        {
            get
            {
                return this._Identifier;
            }
            set
            {
                this.OnIdentifierChanging(value);
                this._Identifier = value;
                this.OnIdentifierChanged();
                this.OnPropertyChanged("Identifier");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identifier;
        partial void OnIdentifierChanging(string value);
        partial void OnIdentifierChanged();
        /// <summary>
        /// There are no comments for Property SegNum in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short SegNum
        {
            get
            {
                return this._SegNum;
            }
            set
            {
                this.OnSegNumChanging(value);
                this._SegNum = value;
                this.OnSegNumChanged();
                this.OnPropertyChanged("SegNum");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _SegNum;
        partial void OnSegNumChanging(short value);
        partial void OnSegNumChanged();
        /// <summary>
        /// There are no comments for Property SegType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> SegType
        {
            get
            {
                return this._SegType;
            }
            set
            {
                this.OnSegTypeChanging(value);
                this._SegType = value;
                this.OnSegTypeChanged();
                this.OnPropertyChanged("SegType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _SegType;
        partial void OnSegTypeChanging(global::System.Nullable<byte> value);
        partial void OnSegTypeChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property StartOfMessage in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> StartOfMessage
        {
            get
            {
                return this._StartOfMessage;
            }
            set
            {
                this.OnStartOfMessageChanging(value);
                this._StartOfMessage = value;
                this.OnStartOfMessageChanged();
                this.OnPropertyChanged("StartOfMessage");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _StartOfMessage;
        partial void OnStartOfMessageChanging(global::System.Nullable<int> value);
        partial void OnStartOfMessageChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Duration;
        partial void OnDurationChanging(global::System.Nullable<int> value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property NoteDateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> NoteDateTime
        {
            get
            {
                return this._NoteDateTime;
            }
            set
            {
                this.OnNoteDateTimeChanging(value);
                this._NoteDateTime = value;
                this.OnNoteDateTimeChanged();
                this.OnPropertyChanged("NoteDateTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _NoteDateTime;
        partial void OnNoteDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnNoteDateTimeChanged();
        /// <summary>
        /// There are no comments for Property NoteContent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NoteContent
        {
            get
            {
                return this._NoteContent;
            }
            set
            {
                this.OnNoteContentChanging(value);
                this._NoteContent = value;
                this.OnNoteContentChanged();
                this.OnPropertyChanged("NoteContent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NoteContent;
        partial void OnNoteContentChanging(string value);
        partial void OnNoteContentChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
